package proyecto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class IngresarPieza extends javax.swing.JFrame {

    daoProducto dao;
    EntidadProducto p;

    /**
     * Creates new form IngresarPieza
     */
    public IngresarPieza() throws SQLException {
        dao = new daoProducto();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textMaterial = new javax.swing.JTextField();
        textCosto = new javax.swing.JTextField();
        textPeso = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        SalirConfirmarButton = new javax.swing.JToggleButton();
        SalirSinConfirmarButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Material:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, 30));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Peso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, 30));

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, 30));

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NUEVA PIEZA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, 30));

        jLabel6.setBackground(new java.awt.Color(153, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tela 2 tipica.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 350));

        textMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(textMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 180, -1));

        textCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCostoActionPerformed(evt);
            }
        });
        getContentPane().add(textCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 180, -1));

        textPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPesoActionPerformed(evt);
            }
        });
        getContentPane().add(textPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 180, -1));

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        getContentPane().add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 180, -1));

        AgregarButton.setText("Agregar");
        AgregarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarButtonMouseClicked(evt);
            }
        });
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, 40));

        SalirConfirmarButton.setText("Salir/Confirmar");
        SalirConfirmarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirConfirmarButtonMouseClicked(evt);
            }
        });
        SalirConfirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirConfirmarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SalirConfirmarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 130, 40));

        SalirSinConfirmarButton.setText("Salir/No Confirmar");
        SalirSinConfirmarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirSinConfirmarButtonMouseClicked(evt);
            }
        });
        SalirSinConfirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSinConfirmarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SalirSinConfirmarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Corinto.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaterialActionPerformed

    private void textCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCostoActionPerformed

    private void textPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPesoActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void SalirConfirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirConfirmarButtonActionPerformed
        try {
            dao.confirmar();
            
            new Inventario().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(IngresarPieza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalirConfirmarButtonActionPerformed

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        String nombre = textNombre.getText();
        String material = textMaterial.getText();
        float costo = Float.valueOf(textCosto.getText());
        float peso = Float.valueOf(textPeso.getText());

        p = new EntidadProducto(0, nombre, false, 0, material, null, costo, peso);
        if (dao.create(p)) {
            JOptionPane.showMessageDialog(this, "Se insertó el producto exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se insertó registro");
        }

        limpiarCampos();
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void AgregarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarButtonMouseClicked

    }//GEN-LAST:event_AgregarButtonMouseClicked

    private void SalirConfirmarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirConfirmarButtonMouseClicked

    }//GEN-LAST:event_SalirConfirmarButtonMouseClicked

    private void SalirSinConfirmarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirSinConfirmarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirSinConfirmarButtonMouseClicked

    private void SalirSinConfirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSinConfirmarButtonActionPerformed
        try {
            dao.cancelar();
            
            Inventario a = new Inventario();
            a.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(IngresarPieza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalirSinConfirmarButtonActionPerformed

    public void limpiarCampos() {
        textNombre.setText("");
        textMaterial.setText("");
        textCosto.setText("");
        textPeso.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IngresarPieza().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(IngresarPieza.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JToggleButton SalirConfirmarButton;
    private javax.swing.JToggleButton SalirSinConfirmarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textCosto;
    private javax.swing.JTextField textMaterial;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPeso;
    // End of variables declaration//GEN-END:variables
}
