package proyecto;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jsant
 */
public class Venta extends javax.swing.JFrame {

    daoVentas dao;

    /**
     * Creates new form Venta
     */
    public Venta() throws SQLException {
        dao = new daoVentas();
        initComponents();
//        llenarProductos();
        llenarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textDescuento = new javax.swing.JTextField();
        textVendedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbxUsuarios = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        SalirConfirmar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VENTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        textPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(textPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        textFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaActionPerformed(evt);
            }
        });
        getContentPane().add(textFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descuento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));
        getContentPane().add(textDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 160, -1));

        textVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(textVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });
        getContentPane().add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tela 2 tipica.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 330));

        jButton2.setText("Registrar venta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 160, 40));

        cbxUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxUsuariosItemStateChanged(evt);
            }
        });
        cbxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(cbxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Vendedor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        SalirConfirmar.setText("Salir/Confirmar");
        SalirConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(SalirConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 130, 40));

        jButton4.setText("Salir/No Confirmar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 130, 40));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Corinto.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProductosActionPerformed

    private void cbxProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProductosItemStateChanged

    }//GEN-LAST:event_cbxProductosItemStateChanged

    private void llenarUsuarios() throws SQLException {
        daoUsuario usuario = new daoUsuario();
        ArrayList<EntidadUsuario> listaUsuarios = usuario.read();

        cbxUsuarios.removeAllItems();

        for (int i = 0; i < listaUsuarios.size(); i++) {
            cbxUsuarios.addItem(new EntidadUsuario(listaUsuarios.get(i).getID(), listaUsuarios.get(i).getNombre()));
        }
    }

    private void llenarProductos() {
        try {
            daoProducto producto = new daoProducto();
            ArrayList<EntidadProducto> listaProductos = producto.read();

            cbxUsuarios.removeAllItems();
            for (int i = 0; i < listaProductos.size(); i++) {
                cbxUsuarios.addItem(new EntidadUsuario(listaProductos.get(i).getID(), listaProductos.get(i).getNombre()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cbxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUsuariosActionPerformed

    private void textPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Registrar venta   
        EntidadVenta p;

        float precio = Float.parseFloat(textPrecio.getText());
        int descuento = Integer.parseInt(textDescuento.getText());
        int vendedorID = Integer.parseInt(textVendedor.getText());
        int usuarioID = Integer.parseInt(textID.getText());

        p = new EntidadVenta(0, precio, null, descuento, vendedorID, usuarioID);
        if (dao.create(p)) {
            JOptionPane.showMessageDialog(this, "Se insertó la venta exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se insertó la venta");
        }

        limpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaActionPerformed

    private void textVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVendedorActionPerformed

    private void cbxUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxUsuariosItemStateChanged
        int id = cbxUsuarios.getItemAt(cbxUsuarios.getSelectedIndex()).getID();
        String idS = id + "";
        textID.setText(idS);
    }//GEN-LAST:event_cbxUsuariosItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void SalirConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirConfirmarActionPerformed
        dao.confirmar();
        Principal a = new Principal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirConfirmarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dao.cancelar();

        Principal a = new Principal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    public void limpiarCampos() {
        textPrecio.setText("");
        textDescuento.setText("");
        textVendedor.setText("");
        textID.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Venta().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton SalirConfirmar;
    private javax.swing.JComboBox<EntidadUsuario> cbxUsuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textDescuento;
    private javax.swing.JTextField textFecha;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textVendedor;
    // End of variables declaration//GEN-END:variables
}
